ALTER TABLE `Sale`
  MODIFY COLUMN `type` ENUM('PLOT','SHOP','LAND','FLAT','PLOT_WIRE','SHOP_WIRE') NULL;

ALTER TABLE `Inventory`
  MODIFY COLUMN `type` ENUM('PLOT','SHOP','LAND','FLAT','PLOT_WIRE','SHOP_WIRE') NOT NULL DEFAULT 'PLOT';
